use std::env;
use std::fs;
use std::path::PathBuf;

const FANOUT: usize = 4;
const DEPTH: usize = 5;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set"));
    let mut generated = String::new();
    generated.push_str("// Generated by fixtures/complex-tree/build.rs.\n");
    generated.push_str("#[inline(never)]\n");
    generated.push_str("pub fn tree_root(seed: usize) -> usize {\n");
    generated.push_str("    let local = [seed; 7];\n");
    generated.push_str("    std::hint::black_box(&local);\n");
    generated.push_str("    let child = node_0_0(seed.wrapping_add(local.len()));\n");
    generated.push_str("    std::hint::black_box(child.wrapping_add(local.len()))\n");
    generated.push_str("}\n\n");
    for depth in 0..=DEPTH {
        let width = FANOUT.pow(depth as u32);
        for index in 0..width {
            write_node(&mut generated, depth, index);
        }
    }
    fs::write(out_dir.join("generated_calls.rs"), generated)
        .expect("generated call tree can be written");
}

fn write_node(generated: &mut String, depth: usize, index: usize) {
    let local_words = 4 + ((depth + index) % 29);
    generated.push_str("#[inline(never)]\n");
    generated.push_str(&format!("pub fn node_{depth}_{index}(seed: usize) -> usize {{\n"));
    generated.push_str(&format!(
        "    const UNIQUE: usize = {};\n",
        depth * 100_000 + index
    ));
    generated.push_str(&format!("    let local = [seed; {local_words}];\n"));
    generated.push_str("    std::hint::black_box(&local);\n");
    if depth < DEPTH {
        generated.push_str("    let mut acc = seed.wrapping_add(local.len()).wrapping_add(UNIQUE);\n");
        for child in 0..FANOUT {
            let child_index = index * FANOUT + child;
            generated.push_str(&format!(
                "    acc = acc.wrapping_add(node_{}_{child_index}(acc.wrapping_add({child})));\n",
                depth + 1
            ));
        }
    } else {
        generated.push_str("    let acc = seed.wrapping_add(local.len()).wrapping_add(UNIQUE);\n");
    }
    generated.push_str("    std::hint::black_box(acc)\n");
    generated.push_str("}\n\n");
}
